name: cricket_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cric-0.png
    - assets/images/cric-1.png
    - assets/images/cric-2.png
    - assets/images/cric-3.png
    - assets/images/cric-4.png
    - assets/images/cric-5.png
    - assets/images/cric-6.png
